# 第五章 pandas入门

padans是用来处理表格型和异质型数据，numpy更适合处理同质型

In [1]:
import pandas as pd
from pandas import Series,DataFrame

## 5.1 pandas数据结构介绍

### 5.1.1 Series
series是一种一维的数组型对象，它包含了一个值序列（与numpy中的类型类似），并且包含了数据标签，称为索引。

In [2]:
# 最简单的序列
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
# 直接指定每一行的索引
obj2 = pd.Series([4,7,-5,3],index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
# 通过标签选取行
obj2['a']

-5

In [7]:
obj2['d']

4

In [8]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [9]:
# 通过布尔值数据过滤
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [10]:
# 与标量相乘
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [11]:
# 应用数据函数
import numpy as np
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [12]:
# 从另一个角度考虑，可以认为Series是一个长度固定而且有序的字典，因为它将索引值和数据值按位置进行配对
'b' in obj2

True

In [13]:
'e' in obj2

False

In [14]:
# 可以直接将python的字典类型转为Series 并且按照索引已经排序咯
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [15]:
# 同样可以将字典键按照想要的顺序传入 输出的NaN是pandas中标记缺失值或者NA值得方式
states = ['California','Ohio','Oregon','Texas']
obj4 = pd.Series(sdata,index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [16]:
# pandas中使用isnull和notnull函数来检查缺失数据，就是NA或者缺失的情况
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [17]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [18]:
# 也可以对实例调用方法
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [19]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
# 对很多应用，在数学操作中自动对齐索引是Series的一个非常有用的特性
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [21]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [22]:
# 这里对于两个series中，有交集的内容自动对齐计算
# 这个特性和数据库中的join相似，但是保留了不匹配的项目
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [23]:
# Series对象自身和其索引都有name属性，这个特点很有用哟
obj4.name = 'population'
obj4.index.name='state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [24]:
# Series的索引可以通过按位置赋值的方式进行改变
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [25]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [26]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 5.1.2 DataFrame
dataframe表示的是矩阵的数据表，它包含已排序的列集合，每一列可以是不同的值类型。DataFrame既有行索引也有列索引，它可以被视为一个共享相同索引的Series的字典。尽管DataFrame是二维的，但你可以利用分层索引在DataFrame中展现更高维度的数据。

In [27]:
# 有很多中方式创建DataFrame,最常用的方式是利用包含等长度列表或Numpy数组的字典来形成DataFrame
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year':[2000,2001,2002,2001,2002,2003],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [28]:
# 选出头5行
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [29]:
# 可以指定列的顺序
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [30]:
# 指定行标签，指定列标签顺序，如果标签不存在则出现缺失值NAN 行标签一定不能大于本身的行长度
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [31]:
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [32]:
# 选取一个列
# DataFrame中的一列，可以按字典型标记或属性那样检索为Series 相当于pandas的一列就是一个Series
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [33]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [34]:
# 行也可以通过loc进行选取
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [35]:
# 列的引用的修改 可以赋值为标量值或者值数组
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [36]:
# 传入的数组长度必须和DataFrame的长度相同
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [37]:
# 给指定位置赋值
val = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [38]:
# 如果被赋值的列不存在，则生成一个新列，同时del关键字可以像在字典中一样删除DataFrame的列
# frame2.eastern 无法创建新的列
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [39]:
# del
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

从DataFrames中选取的列是数据的视图，而不是拷贝。因此，对Series的修改会映射到DataFrame中。如果需要复制，则应当显示的使用Series的copy方法。

**另外一种常用的数据形式是包含字典的嵌套字典：**

In [40]:
pop = {
    'Nevada':{2001:2.4,2002:2.9},
    'Ohio':{2000:1.5,2001:1.7,2002:3.6}
    
}
# 如果嵌套字典传入DataFrame,pandas会将外部字典的键作为列，将内部字典的键作为行
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [41]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [42]:
# 对pd进行显示的指定索引顺序
pd.DataFrame(pop,index=[2001,2002,2003])


AttributeError: 'list' object has no attribute 'astype'

In [43]:
# 包含Series的字典也可以用于构造DataFrame
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

**更多的可以向DataFrame转化的对象列表，参看P133表5-1**

In [44]:
# DataFrame的索引和列拥有name属性
frame3.index.name = 'year';frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [45]:
# 和Series类似,DataFrame的values属性会将包含在DataFrame中的数据以二维ndarray的形式返回
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [46]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [47]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64', name='year')

In [48]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [49]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [50]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64', name='year')

### 5.1.3 索引对象
pandas中的索引对象是用于存储轴标签和其他元数据的。

In [51]:
obj = pd.Series(range(3),index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [52]:
index[1:]

Index(['b', 'c'], dtype='object')

In [53]:
# 索引对象是不可变的
index[1] = 'd'

TypeError: Index does not support mutable operations

In [54]:
# 索引对象的不可变性，使得分享该对象更为安全
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [55]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [56]:
obj2.index is labels

True

In [57]:
# 索引对象 也像一个固定大小的集合
frame3


state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [58]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [59]:
'Ohio' in frame3.columns

True

In [60]:
2003 in frame3.index

False

In [61]:
# 与python集合不同的，pandas索引对象可以包含重复标签
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

**P135表5-2 索引对象的方法和属性**

## 5.2 基本功能
主要了解Series或DataFrame中的数据交互的基础机制。

### 5.2.1 重建索引
reindex用于创建一个符合新索引的新对象，很重要的方法


In [62]:
# 在Series中的表现
obj =pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [63]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [64]:
# 对于顺序数据，比如时间序列，重建时很可能需要插值或填值。method可选参数允许我们使用注入ffill等方法在重建索引时插值，ffill方法会将值向前填充。
obj3 =pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [65]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [66]:
# 在DataFrame中，reindex可以改变行索引，列索引，也可以同时改变两者。
# 当仅传入一个序列时，结果中的行会重建索引
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [67]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [68]:
states = ['Texas','Utah','California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [69]:
# 对更改索引时，人们更倾向于用loc进行行列标签的同时reindex
frame.loc[['a','b','c','d'],states]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [70]:
frame.reindex(['a','b','c','d'],states)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Interpreting call
	'.reindex(a, b)' as 
	'.reindex(index=a, columns=b)'.
Use named arguments to remove any ambiguity. In the future, using positional arguments for 'index' or 'columns' will raise  a 'TypeError'.
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [71]:
frame.reindex(index=['a','b','c','d'],columns=states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

**p137 表5-3 reindex方法的参数**

### 5.2.2 轴向上删除条目
drop 方法会返回一个含有指示值或轴向上删除值的新对象

In [72]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [73]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [74]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [75]:
# 在DataFrame中，索引值可以从轴向上删除。
data = pd.DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [76]:
# 调用drop时使用标签序列会根据行标签删除值(轴0)
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [77]:
# 可以通过传递axis=1或axis='columns'来从列中删除值
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [78]:
data.drop(['two','three'],axis='columns')

one  four
Ohio        0     3
Colorado    4     7
Utah        8    11
New York   12    15

**很多方法，包括drop会修改Series或DataFrame的尺寸或形状，这些方法直接操作原对象而不返回新对象**

In [79]:
# inplace属性会清理被删除的数据
obj.drop('c',inplace=True)

In [80]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### 5.2.3 索引，选择与过滤
Series的索引和numpy的类似，只是其值可以不是整数

In [81]:
# 对Series
obj = pd.Series(np.arange(4.),index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [82]:
obj['b'];obj[1]

1.0

In [83]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [84]:
obj[['d','c','d']]

d    3.0
c    2.0
d    3.0
dtype: float64

In [85]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [86]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [87]:
# 普通的python切片是 左闭右开的，但是Series的切片是左闭右闭的
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [88]:
# 使用取索引的方法，再设置值会修改原对象
obj['b':'c']=5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [89]:
# 在DataFrame中 索引的表现
data = pd.DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [90]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [91]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [92]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [93]:
# 布尔数组选行
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [94]:
# 布尔数组选元素
data[data>5]

one   two  three  four
Ohio       NaN   NaN    NaN   NaN
Colorado   NaN   NaN    6.0   7.0
Utah       8.0   9.0   10.0  11.0
New York  12.0  13.0   14.0  15.0

#### 5.2.3.1 使用loc和iloc选择数据
针对DataFrame在行上的标签索引，使用loc和iloc，loc用于取轴标签，iloc用于取整数标签

In [95]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [96]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [97]:
# 出了单个标签或标签列表之外，索引功能还可以用于切片
data.loc[:'Utah','two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [98]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

**pandas中对Series和DataFrame进行选择和重排的方式有很多，可以任意组合**
推荐使用loc来进行,行的索引。

**P143,表5-4 DataFrame索引选项**
df.at[label_i,label_j]
df.iat[i,j]
get_value,set_value

### 5.2.4 整数索引
在pandas对象上使用整数索引，可能会有歧义，因为它和在列表和元组等内建的数据结构进行索引有些许不同。

In [99]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [100]:
# 这里出错时因为pandas的索引并不能像内建数据类型一样
ser[-1]

KeyError: -1

In [101]:
# 对于索引是非整数的
ser2 = pd.Series(np.arange(3.),index=['a','b','c'])
ser2[-1]

2.0

In [102]:
# 为了保持一致性，当你有一个包含整数的轴索引时，数据选择时始终使用标签索引
ser[:1]

0    0.0
dtype: float64

In [103]:
# 这里的标签索引左闭右闭
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [104]:
# 整数索引和python一样，左闭右开
ser.iloc[:1]

0    0.0
dtype: float64

### 5.2.3 算术和数据对齐
当你将对象相加时，如果存在某个索引对不相同，则返回结果的索引将是索引对的并集。像outer join一样


In [105]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [106]:
#有相同索引的进行操作，其他置为NAN
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [107]:
(s1+s2).isnull();(s1+s2).notnull()

a     True
c     True
d    False
e     True
f    False
g    False
dtype: bool

In [108]:
# 对于DataFrame 行和列都会执行对齐
df1 = pd.DataFrame(np.arange(9.).reshape(3,3),columns=list('bcd'),index=['Ohio','Texas','Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [109]:
df1 =pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[1,2]})
df1+df2

A   B
0 NaN NaN
1 NaN NaN

In [110]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

#### 5.2.5.1 使用填充值的算术方法
就是算法操作出现NaN的时候，可以指定fill_value

In [111]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))
df2.loc[1,'b'] = np.nan

In [112]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [113]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [114]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [115]:
# 如果想自己控制缺失值，使用df对象的实例方法add
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [116]:
# series和df的算法方法中，都有一个以r开头的，其代表对传入的算法的参数进行翻转
1/df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [117]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [118]:
# 在对series和df进行重建索引时，也可以指定不同的填充值
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### 5.2.5.2 DataFrame和Series间的操作


In [119]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [120]:
arr[0]

array([0., 1., 2., 3.])

In [121]:
# 当我们从arr中减去arr[0]时，减法在每一行都进行了操作，这就是所谓的广播机制
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [122]:
frame = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [123]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [124]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [125]:
# 如果一个索引值不再DataFrame的列中，也不在Series的索引中，则对象会重建索引应形成联合
series2 = pd.Series(range(3),index=list('bef'))
series2

b    0
e    1
f    2
dtype: int64

In [126]:
# 重建索引并联合
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [127]:
# 如果想改为在列上进行广播，在行上匹配，必须使用算法方法
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [128]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [129]:
frame.sub(series3,axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 5.2.6 函数应用和映射
numpy的通用函数对pandas对象也有效

In [130]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    0.176711 -0.748528 -0.369937
Ohio    0.490799 -0.236221  0.710486
Texas   0.049628  1.000060 -0.124686
Oregon -0.271890 -1.091813  0.249669

In [131]:
np.abs(frame)

b         d         e
Utah    0.176711  0.748528  0.369937
Ohio    0.490799  0.236221  0.710486
Texas   0.049628  1.000060  0.124686
Oregon  0.271890  1.091813  0.249669

In [132]:
# 另外一个常用的操作时将函数应用到一行或一列的一位数组上，apply方法
# 这里的函数f 可以计算Series最大值和最小值的差，会被frame中的每一列调用一次 结果是一个以frame的列作为索引的series
f = lambda x:x.max()-x.min()
frame.apply(f)

b    0.762689
d    2.091873
e    1.080423
dtype: float64

In [133]:
# 如果你传递axis = 'columns'给apply函数，函数将被每行调用
frame.apply(f,axis='columns')

Utah      0.925239
Ohio      0.946708
Texas     1.124746
Oregon    1.341482
dtype: float64

In [134]:
# 大部分最常用的数组统计sum,mean等，都是df的方法，所以使用时可以不用apply
# 传递给apply的函数并不一定要返回一个标量，可以返回一个series
def f(x):
    return pd.Series([x.min,x.max()],index=['min','max'])
frame.apply(f)

b  \
min  <bound method Series.min of Utah      0.176711...   
max                                           0.490799   

                                                     d  \
min  <bound method Series.min of Utah     -0.748528...   
max                                            1.00006   

                                                     e  
min  <bound method Series.min of Utah     -0.369937...  
max                                           0.710486

In [135]:
# 逐元素的python函数也可以使用，假设你想要根据frame中的每个浮点数计算一个格式化字符串，可以使用applymap
format = lambda x: '%.2f'%x
frame.applymap(format)

b      d      e
Utah     0.18  -0.75  -0.37
Ohio     0.49  -0.24   0.71
Texas    0.05   1.00  -0.12
Oregon  -0.27  -1.09   0.25

In [136]:
# series 也有类似方法 map
frame['e'].map(format)

Utah      -0.37
Ohio       0.71
Texas     -0.12
Oregon     0.25
Name: e, dtype: object

### 5.2.7 排序和排名
根据某些准则对数据集进行排序是很重要的。


In [137]:
# sort_index() 按行或列索引进行字典型排序，该方法返回一个新的排序好的对象
obj =pd.Series(range(4),index=list('dabc'))
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [138]:
# df中根据各个轴进行排序
frame = pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=list('dabc'))
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [139]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [140]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [141]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [142]:
# 如果需要对series的值进行排序，使用sort_values方法
obj = pd.Series([4,7,-3,2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [143]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [144]:
# 当对df使用sort_values的时候，需要将一个或多个列传入函数
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [145]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [146]:
# 原理和数据库中的order by多个元素一样
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [147]:
# 排名是指对数组从1到有效数据点总数分配名词的操作。rank
# 0和2 位置的元素的排名，相当于 （6+7）/2
obj = pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [148]:
# 也可以根据观测顺序来进行分配
# 第0个为 6 是因为它比第2个更先出现
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [149]:
# 按照降序排序
# method='max' 打破平级关系的方法是 对整个组使用最大排名
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [150]:
frame = pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [151]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [152]:
frame.rank(axis='index')

b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

**P155表5-6中记录了 排名中的平级关系打破方法**

## 5.2.8 含有重复标签的轴索引

In [153]:
# 带有重复索引的series
obj = pd.Series(range(5),index = ['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [154]:
# 索引的 is_unique属性 检查标签是否唯一
obj.index.is_unique

False

In [155]:
obj['a']

a    0
a    1
dtype: int64

In [156]:
obj['c']

4

In [157]:
# 相同的逻辑 也可以扩展到df中
df = pd.DataFrame(np.random.randn(4,3),index=list('aabb'))
df

0         1         2
a -0.724562 -0.744070 -0.723954
a -0.575356 -0.621430  1.251514
b -1.101096  0.336044  0.619168
b  0.215268  0.100518 -0.766247

In [158]:
df.loc['b']

0         1         2
b -1.101096  0.336044  0.619168
b  0.215268  0.100518 -0.766247

## 5.3 描述性统计的概述与计算
pandas对象装配了一个常用数学，统计学方法的集合。其中大部分属于规约或汇总统计的类别，这些方法从DataFrame的行或列中抽取一个Series或一系列值得单个值（如总和或平均值）

In [159]:
# 内建了处理缺失值得功能
df= pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=list('abcd'),columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [160]:
# 调用df的sum方法返回一个包含列上加和的series
df.sum()

one    9.25
two   -5.80
dtype: float64

In [161]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [162]:
# 对于算术操作，除非整个切片上都是NA，否则NA值是被自动排除的，可以通过金庸skipna来实现不排除NA值。
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [163]:
# 间接统计信息，比如最大最小值的索引值
df.idxmax()

one    b
two    d
dtype: object

In [164]:
# 除了规约方法，还有积累型
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [165]:
# 还有的就是既不是规约也不是积累。
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [166]:
# 对于非数值数据,describe生成另一种统计
obj=pd.Series(['a','a','b','b','c']*4)
obj

0     a
1     a
2     b
3     b
4     c
5     a
6     a
7     b
8     b
9     c
10    a
11    a
12    b
13    b
14    c
15    a
16    a
17    b
18    b
19    c
dtype: object

In [167]:
obj.describe()

count     20
unique     3
top        a
freq       8
dtype: object

**P159 表5-8 描述性统计和汇总统计**

### 5.3.1 相关性和协方差


In [168]:
import pandas_datareader.data as web

In [169]:
all_data = {ticker:web.get_data_yahoo(ticker) for ticker in ['AAPL','IBM','MSFT','GOOG']}

In [170]:
price = pd.DataFrame({ticker:data['Adj Close'] for ticker,data in all_data.items()})

In [171]:
volume = pd.DataFrame({ticker:data['Volume'] for ticker,data in all_data.items()})

In [172]:
returns = price.pct_change()

In [174]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2019-07-29  0.009339 -0.003171 -0.002193 -0.008797
2019-07-30 -0.004292 -0.007357 -0.004822 -0.011514
2019-07-31  0.020404 -0.010216 -0.029070 -0.006905
2019-08-01 -0.021639  0.014031  0.013136 -0.006304
2019-08-02 -0.021158 -0.020423 -0.008402 -0.012423

In [175]:
# series 的corr方法 是计算两个series中重叠的，非NA的，按索引对齐的值的相关性
# 相应的cov计算的是协方差
returns['MSFT'].corr(returns['IBM'])


0.48642448999988125

In [176]:
returns['MSFT'].cov(returns['IBM'])

8.633267747918666e-05

In [177]:
# DATAFREAM的corr和cov方法以df方式返回相关性和协方差的矩阵。
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.378498  0.451084  0.457257
IBM   0.378498  1.000000  0.486424  0.399875
MSFT  0.451084  0.486424  1.000000  0.533791
GOOG  0.457257  0.399875  0.533791  1.000000

In [178]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000265  0.000076  0.000106  0.000116
IBM   0.000076  0.000151  0.000086  0.000076
MSFT  0.000106  0.000086  0.000208  0.000120
GOOG  0.000116  0.000076  0.000120  0.000242

In [179]:
returns.corrwith(returns.IBM)

AAPL    0.378498
IBM     1.000000
MSFT    0.486424
GOOG    0.399875
dtype: float64

In [180]:
returns.corrwith(volume)

AAPL   -0.062038
IBM    -0.150972
MSFT   -0.090047
GOOG   -0.018750
dtype: float64

### 5.3.2 唯一值，计数和成员属性


In [185]:
# 从一维series包含的数值中提取信息 
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [187]:
uniques.sort()
uniques

array(['a', 'b', 'c', 'd'], dtype=object)

In [188]:
# 计算值出现的次数
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [190]:
# value_counts也是pd的顶层函数
pd.value_counts(obj,sort=False)

c    3
d    1
a    3
b    2
dtype: int64

In [191]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [192]:
mask = obj.isin(['b','c'])

In [193]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [194]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [196]:
# 与isin相关的Index.get_indexer方法，可以提供一个索引数组，这个索引数组可以将可能非唯一数组转换为另一个唯一值数组
to_match = pd.Series(['c','a','b','b','c','a'])
unique_vals = pd.Series(['c','b','a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

**P163表5-9 唯一值，计数和集合成员属性方法**

In [197]:
data = pd.DataFrame({'Qu1':[1,3,4,3,4],
                     'Qu2':[2,3,1,2,3],
                     'Qu3':[1,5,2,4,4]})

In [198]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [199]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0